export interface User { // This User interface can be moved to a shared types file if used elsewhere
  id: string; // Typically generated by the backend/database
  username: string;
  email: string;
  // Password/hash handled by backend
}

export interface Avatar {
  rpm_avatar_id: string; // Assigned by the backend upon saving
  glb_url: string;
}

export interface AvatarInstance {
  id?: string; // Assigned by the backend
  userId: string;
  avatarId: string;
  config?: Record<string, any>; // User-specific configuration for this avatar instance
}